spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/practice_batch?serverTimezone=Asia/Seoul
    username: batch_user
    password: batch_password
    driver-class-name: com.mysql.cj.jdbc.Driver